# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication
from view.window import WorkingWindow
import sys


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = WorkingWindow()
    ui.main_window.show()
    sys.exit(app.exec_())
