# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from data.db_access import DbManager
from data.data_models import User


class Dialog(object):
    """Ventana de diálogo para ingreso de nombre de nuevo usuario.
    """
    def __init__(
        self,
    ) -> None:
        self.dialog = QtWidgets.QDialog()
        self.dialog.setObjectName("Dialog")
        self.dialog.resize(400, 209)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 361, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_new_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_new_user.setObjectName("label_new_user")
        self.verticalLayout.addWidget(
            self.label_new_user,
            0,
            QtCore.Qt.AlignHCenter
        )
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 361, 22))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2
        )
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 90, 361, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3
        )
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.line_new_user = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.line_new_user.setMinimumSize(QtCore.QSize(271, 0))
        self.line_new_user.setPlaceholderText("")
        self.line_new_user.setObjectName("line_new_user")
        self.verticalLayout_3.addWidget(self.line_new_user)

        QtCore.QMetaObject.connectSlotsByName(self.dialog)

        self.dialog.setWindowTitle("Nuevo Usuario")
        self.label_new_user.setText("Ingrese el nombre del nuevo usuario:")


class NewUserController(Dialog):
    """Controlador de ventana de diálogo para creación de nuevo usuario.
    """
    def __init__(self) -> None:
        """Se crea una instancia del gestor de Db y se establecen las
        acciones por botón.
        """
        super().__init__()

        self.dbm = DbManager()
        self.buttonBox.accepted.connect(self.new_user_accept)
        self.buttonBox.rejected.connect(self.new_user_cancel)

    def update_user_list(self):
        pass

    def new_user_accept(self):
        """Si se introduce una string como nombre y se oprime
        aceptar, se guarda el nombre de usuario en la DB.
        """
        print('Getting info about new user')
        user_name = self.line_new_user.text()
        if user_name != '':
            user = User(user_name=user_name)
            self.dbm.create_user(user)
            print(f'User {user.user_name} created')

        self.update_user_list()
        self.dialog.close()

    def new_user_cancel(self):
        """Si se oprime cancelar, se cierra el diálogo sin guardar.
        """
        print('New user cancelled.')
        self.dialog.close()
